name: Create PR test
# Invocable as a reusable workflow
# Can be manually triggered
on:
  workflow_call: 
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b update-branch

      - name: Make changes
        run: |
          # Add your commands to make changes here
          echo "Some changes" > changes.txt
          git add changes.txt
          git commit -m "Add changes"

      - name: Push changes
        run: git push origin update-branch

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Automated PR: Add changes",
              head: "update-branch",
              base: "test-PR",
              body: "This PR was created automatically by GitHub Actions.",
            });
            console.log(`Created PR #${pullRequest.number}`);
